<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net9.0-android</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <RootNamespace>Manta</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCssItems>false</EnableDefaultCssItems>
    <Nullable>enable</Nullable>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>

    <!-- CHANGE THESE -->
    <ApplicationTitle>Haveno</ApplicationTitle>
    <ApplicationId>com.haveno</ApplicationId>
    <DaemonUrl>https://github.com/atsamd21/haveno/releases/download/v1.8.0</DaemonUrl>
    <Network>XMR_STAGENET</Network>
    <HavenoAppName>haveno-dev</HavenoAppName>
    <SimplexLink>https://smp4.simplex.im/g#hr4lvFeBmndWMKTwqiodPz3VBo_6UmdGWocXd1SupsM</SimplexLink>
    <MatrixLink>https://matrix.to/#/#haveno:monero.social</MatrixLink>
    <GitHubLink>https://github.com/atsamd21/Haveno-app</GitHubLink>
    <!-- CHANGE THESE -->

    <!-- Versions -->
    <ApplicationDisplayVersion>1.0.8</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">29.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <RunAOTCompilation>False</RunAOTCompilation>
    <PublishTrimmed>False</PublishTrimmed>
    <JavaMaximumHeapSize>4G</JavaMaximumHeapSize>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
      <_Parameter1>HavenoAppName</_Parameter1>
      <_Parameter2>$(HavenoAppName)</_Parameter2>
    </AssemblyAttribute>

    <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
      <_Parameter1>Network</_Parameter1>
      <_Parameter2>$(Network)</_Parameter2>
    </AssemblyAttribute>

    <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
      <_Parameter1>DaemonUrl</_Parameter1>
      <_Parameter2>$(DaemonUrl)</_Parameter2>
    </AssemblyAttribute>

    <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
      <_Parameter1>SimplexLink</_Parameter1>
      <_Parameter2>$(SimplexLink)</_Parameter2>
    </AssemblyAttribute>

    <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
      <_Parameter1>MatrixLink</_Parameter1>
      <_Parameter2>$(MatrixLink)</_Parameter2>
    </AssemblyAttribute>

    <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
      <_Parameter1>GitHubLink</_Parameter1>
      <_Parameter2>$(GitHubLink)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-android|AnyCPU'">
    <PublishTrimmed>False</PublishTrimmed>
    <JavaMaximumHeapSize>4G</JavaMaximumHeapSize>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <JavaMaximumHeapSize>4G</JavaMaximumHeapSize>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
    <JavaMaximumHeapSize>4G</JavaMaximumHeapSize>
  </PropertyGroup>

  <ItemGroup>
    
    <!-- CHANGE THESE -->
    <MauiIcon Include="Resources\AppIcon\appiconfg.svg" ForegroundFile="Resources\AppIcon\appicon.svg" Color="#FFFFFF" ForegroundScale="0.80" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#000000" BaseSize="512,256" />
    <!-- CHANGE THESE -->

    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />

    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />

    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <AndroidResource Remove="Enums\**" />
    <AndroidResource Remove="Platforms\Android\JniLibs\arm64\**" />
    <Compile Remove="Enums\**" />
    <Compile Remove="Platforms\Android\JniLibs\arm64\**" />
    <Content Remove="Enums\**" />
    <Content Remove="Platforms\Android\JniLibs\arm64\**" />
    <EmbeddedResource Remove="Enums\**" />
    <EmbeddedResource Remove="Platforms\Android\JniLibs\arm64\**" />
    <MauiXaml Remove="Enums\**" />
    <MauiXaml Remove="Platforms\Android\JniLibs\arm64\**" />
    <None Remove="Enums\**" />
    <None Remove="Platforms\Android\JniLibs\arm64\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="install_haveno.sh" />
    <None Remove="Platforms\Android\Resources\xml\net_sec_conf.xml" />
    <None Remove="Resources\AppIcon\appiconfg.svg" />
  </ItemGroup>

  <ItemGroup>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\arm64-v8a\libprootwrapper.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\arm64-v8a\libproot.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\arm64-v8a\libloader.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\arm64-v8a\libloader32.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\armeabi-v7a\libprootwrapper.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\armeabi-v7a\libloader.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\armeabi-v7a\libproot.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>


    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\x86_64\libprootwrapper.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\x86_64\libloader.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\x86_64\libloader32.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms\Android\JniLibs\x86_64\libproot.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidNativeLibrary>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\Pages\BuySell.razor.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
    <PackageReference Include="CommunityToolkit.Maui" Version="12.3.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.76.0" />
    <PackageReference Include="HavenoSharp" Version="1.1.15" Condition="'$(Configuration)' == 'Release'" />    
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.AutoActivation" Version="9.10.0" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.120" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.120" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="9.0.120" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.13" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="ZXing.Net.Maui" Version="0.6.0" />
    <PackageReference Include="ZXing.Net.Maui.Controls" Version="0.6.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <ProjectReference Include="../HavenoSharp/HavenoSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Platforms\Android\Assets\" />
    <Folder Include="wwwroot\fonts\" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\build-android.yml" />
    <None Include=".github\workflows\build.yml" />
    <None Include="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android'">
    <PackageReference Include="Xamarin.AndroidX.Work.Runtime">
      <Version>2.8.0</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Update="CameraPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>
  
</Project>
